import {StyleSheet} from 'react-native';

export default StyleSheet.create({
    conteiner:{
        flex:1,
        backgroundColor:'#fff',
        alignItems:'center',
        justifyContent:'center',
    },
    textoCursos:{
        color:'#00f',
        fontSize:15,
    },
    textoTitulo:{
        color:'#000',
        fontSize:30,
    },
    textoPadrao:{
        color:'#f00',
        fontSize:30,
    },
    logo:{
        width:250,
        height:250,
        resizeMode:'contain',
    },
    imagemFundo:{
        flex:1,
        resizeMode:"cover",
        width:"100%",
    },
    botao:{
        alignItems:"center",
        backgroundColor:"#ccc",
        padding:10,
    },
    mod:{
        backgroundColor:"#222",
        margin:20,
        padding:20,
        borderRadius:20,
        elevation:10,
    },
    textoMod:{
        color:"#fff",
    }
})
